apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-main
  namespace: argocd
spec:
  project: default
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mirafzal/argocd-private-infra
    path: helm-charts/keycloak-main
    targetRevision: main