apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: infra-app-project
  destination:
    namespace: minio-tenant
    server: https://kubernetes.default.svc
  source:
    repoURL: https://operator.min.io/
    targetRevision: 7.1.1
    chart: tenant
    helm:
      valuesObject:
        tenant:
          name: minio
          image:
            repository: harbor.infra.mirafzal.uz/quay.io/minio/minio
            tag: RELEASE.2025-04-22T22-12-26Z
            pullPolicy: IfNotPresent
        ingress:
          api:
            enabled: true
            ingressClassName: "nginx"
            labels: { }
            annotations: { }
            tls:
              - hosts:
                  - minio-api.infra.mirafzal.uz
                secretName: infra-wildcard-cert
            host: minio-api.infra.mirafzal.uz
            path: /
            pathType: Prefix
          console:
            enabled: true
            ingressClassName: "nginx"
            labels: { }
            annotations: { }
            tls:
              - hosts:
                  - minio-api.infra.mirafzal.uz
                secretName: infra-wildcard-cert
            host: minio-console.infra.mirafzal.uz
            path: /
            pathType: Prefix
